buildAppIcons:
	fvm flutter pub get
	fvm flutter pub run flutter_launcher_icons:main -f flutter_icons.yaml

buildAppSplash:
	fvm flutter pub get
	fvm flutter pub run flutter_native_splash:create --path=flutter_splash.yaml

